package.json
src/core/FusionContext.ts

Root and overlay ref on fusion context

Refs on fusion context

---

README.md
src/app/AppRegistrationContainer.ts
src/core/FusionContext.ts

Also avoid notifying listners and deleting non existing temp app manifests

Update createFusionContext to require refs

---

src/http/apiClients/DataProxyClient.ts
src/http/apiClients/models/dataProxy/AccumulatedContainer.ts
src/http/apiClients/models/dataProxy/index.ts
src/http/hooks/dataProxy/useAccumulated.ts
src/http/hooks/dataProxy/useHandover.ts
src/http/resourceCollections/DataProxyResourceCollection.ts

Hooks for dataproxy accumulated datasets used by MI

---

src/http/apiClients/PeopleClient.ts
src/http/apiClients/models/org/Position.ts
src/http/apiClients/models/org/PositionInstance.ts
src/http/apiClients/models/people/PersonBasePosition.ts
src/http/apiClients/models/people/PersonContract.ts
src/http/apiClients/models/people/PersonDetails.ts
src/http/apiClients/models/people/PersonPosition.ts
src/http/apiClients/models/people/PersonProject.ts
src/http/apiClients/models/people/PersonRole.ts
src/http/apiClients/models/people/PersonRoleScope.ts
src/http/resourceCollections/PeopleResourceCollection.ts
src/index.ts

- Added AssignedPerson to PositionInstance
- People api client now use v3 endpoint for person details
- Odata query to expand positions,roles,contracts

Added AssignedPerson to PositionInstance and improved people api

---

package-lock.json
package.json
src/http/HttpClient/ensureRequestInit.ts
src/http/HttpClient/index.ts
src/http/apiClients/OrgClient.ts
src/http/apiClients/models/org/PositionInstance.ts
src/http/apiClients/models/people/PersonAccountType.ts
src/http/resourceCollections/OrgResourceCollection.ts
src/version.ts
tsconfig.json

Also includes a fusion api version header

Update models and get single position

---

src/auth/AuthContainer.ts

Added a filter to the resources array to make sure that no empty URL strings are evaluated when checking for existing apps.

Added filter on resources to remove empty strings

---

src/http/apiClients/OrgClient.ts
src/http/apiClients/PowerBIClient.ts
src/http/apiClients/ReportClient.ts
src/http/apiClients/index.ts
src/http/apiClients/models/powerbi/PowerBIDashboard.ts
src/http/apiClients/models/powerbi/PowerBIError.ts
src/http/apiClients/models/powerbi/PowerBIGroup.ts
src/http/apiClients/models/powerbi/PowerBIReport.ts
src/http/apiClients/models/report/AccessToken.ts
src/http/apiClients/models/report/ConfigValidation.ts
src/http/apiClients/models/report/EmbedConfig.ts
src/http/apiClients/models/report/EmbedInfo.ts
src/http/apiClients/models/report/Person.ts
src/http/apiClients/models/report/Report.ts
src/http/apiClients/models/report/ReportType.ts
src/http/apiClients/models/report/SecurityRequirement.ts
src/http/apiClients/models/report/SecurityRequirementsPolicy.ts
src/http/apiClients/models/report/index.ts
src/http/resourceCollections/FusionResourceCollection.ts
src/http/resourceCollections/OrgResourceCollection.ts
src/http/resourceCollections/PowerBIResourceCollection.ts
src/http/resourceCollections/ReportResourceCollection.ts
src/http/resourceCollections/ServiceResolver.ts
src/http/resourceCollections/index.ts

Split into one Reports Client and one PowerBI Client
reports client talks to fusion backend. 
PowerBI has a few functions that goes directly to powerBI API.

Added Reports PowerBI API.

---

src/http/apiClients/ReportClient.ts
src/http/apiClients/models/report/EmbedConfig.ts

Imported embedConfig to ReportClient

Exported embedConfig type

---

src/auth/AuthCache.ts
src/auth/AuthContainer.ts
src/core/FusionContext.ts

1. Store current url before redirecting to signin
2. Redirect to stored url when returning from signin
- Log errors when handeling window callback

Improve login redirect

---

src/app/AppContainer.ts
src/core/ContextManager.ts
src/http/apiClients/models/context/ContextManifest.ts

Now only takes in an array of Contexttypes, instead of object of contexType.

Simplified ContextManifest.

---

.gitignore
package-lock.json
package.json
src/core/PeopleContainer.ts
src/index.ts

Make it easier for developers to get the current users profile.
useCurrentPersonDetails()
`const currentUserProfile = useCurrentPersonDetails();`

useCurrentPersonDetails hook

---

package.json
src/http/HttpClient/IHttpClient.ts
src/http/HttpClient/ensureRequestInit.ts
src/http/HttpClient/index.ts

Adds the following methods to the `IHttpClient` interface:
```typescript
postFormAsync<TResponse>(
url: string,
form: FormData,
onProgress?: (percentage: number, event: ProgressEvent<XMLHttpRequestEventTarget>) => void
): Promise<HttpResponse<TResponse>>;
```
```typescript
getBlobAsync<TExpectedErrorResponse>(url: string): Promise<File>;
```
They will be used to upload and download binary data like files and attachments.

Added support for uploading and downloading binary data

---

src/http/apiClients/OrgClient.ts
src/http/apiClients/models/org/OrgProject.ts
src/http/apiClients/models/org/OrgProjectDates.ts
src/http/resourceCollections/OrgResourceCollection.ts
src/index.ts

Updated org project model and api versioning for project search
Update: Extracted project dates to new type def

Org project v2 support 

---

src/core/ContextManager.ts

ContextManager will listen to AppContainer change, then try to resolve context

Resolve context from URL or localstorage

---

src/http/apiClients/models/people/PersonPosition.ts

Depends on a PR to the person service

Add appliesFrom, appliesTo and workload to PersonPosition

---

src/core/ContextManager.ts

use buildUrl in setCurrentContextAsync to update the URL with the new GUID on context change

Update Url when changing context

---

src/core/ContextManager.ts
src/http/apiClients/models/context/ContextManifest.ts

extended ContextManifest with some new optional fields.

changed buildURL to also receive current url.

---

src/app/AppContainer.ts
src/core/ContextManager.ts
src/core/FusionContext.ts
src/http/apiClients/FusionClient.ts
src/http/apiClients/models/fusion/FeatureLogEntryRequest.ts
src/http/resourceCollections/FusionResourceCollection.ts
src/index.ts
src/utils/FeatureLogger.ts
src/utils/fusionConsole.ts

- Automatically logs when app is selected
- Automatically logs when context is selected
- Exposes through simple hook `useFeatureLogger()`

Feature logger

---

src/core/ContextManager.ts

Added context validation when setting context. Making sure that it acutally exists in database

Context Manager - Context Validation

---

src/core/ContextManager.ts

Added try catch to all getContextAsync that did not have one.

added tryCatch to all getContextAsync calls

---

src/app/AppContainer.ts
src/utils/EventEmitter/index.ts

currentApp does not always properly update. 
causing the context selector to not show.

currentApp update fix

---

src/core/ContextManager.ts

useContextHistory was missing in the export list.

export useContextHistory

---

src/core/ContextManager.ts

Adjusted how currentApp is checked. As its still sees old app when moving to portal.

Current app is found after navigating away from it 

---

src/app/AppContainer.ts

change manifest to allow multiple auth sources
BREAKING CHANGE: AppRegistration:auth changed from AppAuth to AppAuth[]

feat(core): allow multiple auth sources

---

src/core/NotificationCenter.tsx

Fixed date string for OData filter for getting unseen notificaitons

Notification center - Fixed date string 

---

src/http/apiClients/InfoClient.ts
src/http/apiClients/index.ts
src/http/apiClients/models/info/QuickFact.ts
src/http/resourceCollections/InfoResourceCollection.ts
src/http/resourceCollections/ServiceResolver.ts
src/http/resourceCollections/index.ts

* add client
* add resource collection
* add models
* update resolver

feat: add client for info app

---

src/auth/AuthContainer.ts

clear token when expired (force login on refresh)

fix: auth token refresh

---

src/http/apiClients/OrgClient.ts

Class instance destruction breaks `this`

fix: Remove class method destruction

---

src/http/apiClients/OrgClient.ts

snapshotResportsTo used projectId instead of snapshotId

fix: Snapshot reports-to used wrong arg

---

src/http/apiClients/OrgClient.ts
src/http/apiClients/models/org/CreateTransientSnapshotRequest.ts
src/http/apiClients/models/org/OrgProject.ts
src/http/apiClients/models/org/OrgSnapshot.ts
src/http/resourceCollections/OrgResourceCollection.ts
src/index.ts

Added snapshot transient endpoint and status to OrgSnapshot model

feat: added snapshot transient endpoint

---

src/http/apiClients/OrgClient.ts
src/http/resourceCollections/OrgResourceCollection.ts

Support for contract position deletion and allow headers

feat: add support for contract position deletion

---

src/http/apiClients/OrgClient.ts

delete and "can delete" endpoints for snapshot

feat: delete snapshot endpoint

---

src/index.ts

exported PersonNotificationSettings model from index

fix: exported model from index

---

src/http/apiClients/ReportClient.ts
src/http/resourceCollections/ReportResourceCollection.ts

checkContextAccess: check if user has access to the projects in the selected context.

Added new endpoint to Report Client.

---

src/http/apiClients/models/org/BasePosition.ts
src/http/apiClients/models/org/Position.ts
src/http/apiClients/models/org/PositionInstance.ts

Position - Added isTaskOwner and changesInDraft property
BasePosition - Added projectType, subDiscipline and settings property
PositionInstance - Added changesInDraft property

fix: updated position, baseposition and instance model

---

src/http/apiClients/models/fusionTasks/PimsTask.ts

fix: update PimsTask model

---

package-lock.json
package.json
src/core/ContextManager.ts
src/http/apiClients/models/context/ContextManifest.ts
src/version.ts

new callback in the ContextManifest filterContexts.
optional callback that takes in the search result from the context selector.
Where you can manipualte and filter the search result if needed.

Context Manager - Filter search results

---

package-lock.json
package.json
src/app/AppContainer.ts
src/auth/AuthContainer.ts
src/core/ContextManager.ts
src/core/FusionContext.ts
src/http/HttpClient/index.ts
src/index.ts
src/utils/telemetry/Performance.ts
src/utils/telemetry/TelemetryLogger.ts
src/utils/telemetry/TelemetryObserver.ts
src/utils/telemetry/hooks.ts
src/utils/telemetry/index.ts

telemetry logger with performance monitor, allows for observable properties to be included in the trace

feat: add observable telemetry

---

src/http/apiClients/BookmarksClient.ts
src/http/apiClients/models/bookmarks/BookmarkResponse.ts

Changing the api version of bookmark service to be 1.0 and also adding "type" to Context model

Bookmark Service API version and model update

---

src/http/apiClients/models/dataProxy/mcPackage/McPackage.ts

New field added to the McPackage model "RFCCShippedDate"

DataProxy - McPackage Model - added field rfocShippedDate

---

src/http/apiClients/models/dataProxy/mcPackage/McPackage.ts

rfocShippedDate was added with wrong name. Corrected to rfccShippedDate

rfocShippedDate was added with wrong name. Corrected to rfccShippedDate

---

src/core/NotificationCenter.tsx

wrap return useNotificationCenter in callback

fix: useNotificationCenter causing endless loop

---

src/http/apiClients/models/dataProxy/mcPackage/McPackage.ts

There is a new field for Mechanical completion needed in the front end

[Dataproxy] - chore: add new field to mc package type

---

src/http/apiClients/models/dataProxy/handover/HandoverQuery.ts

Added type field to HandoverQuery.

chore: add type field to HandoverQuery

---

package-lock.json
package.json
src/app/AppContainer.ts

Changing type from AppManifest to any on type AppRegistration in AppContainer.ts

fix(appcontainer): fixing typing on AppRegistration

---

src/http/apiClients/DataProxyClient.ts
src/http/apiClients/models/dataProxy/index.ts
src/http/apiClients/models/dataProxy/workorder/WorkOrderQueryAndNotification.ts
src/http/resourceCollections/DataProxyResourceCollection.ts

Adding query/notification endpoint for workorder dataproxy.

feat: add query and notification endpoint for workorder dataproxy

---

package-lock.json
package.json
src/http/apiClients/models/report/EmbedConfig.ts

adding support for contrastMode in PowerBI embed config.

feat(report-model): extending type EmbedConfig with contrastMode

---

package-lock.json
package.json
src/http/apiClients/models/org/BasePosition.ts

Added new property to baseposition. Property is set to true by backend if direct requests are required on the position.

fix: added requireDirectRequest to basePositionSettings

---

package-lock.json
package.json
src/utils/telemetry/TelemetryLogger.ts

feat: expose AI

---

package-lock.json
package.json
src/version.ts

Updating signalr to Close: #858.
made a pre-release to test in a portal PR - But no service-messages work i PR but its tested in CI. Let me know and i wil trigger a CI service message test.
https://pr-3736.portal.fusion-dev.net/
The Service messages is the feature in portal using `useSignalRHub`.

chore(signalr): update version to 8.0.0

---

package-lock.json
package.json

Support for eslint@8 to resolve peerdep issues

fix(deps): updates eslint-config-fusion to support eslint@8
