equinor/fusion-api

src/core/FusionContext.ts, src/core/UserMenuSections.ts, src/http/apiClients/PeopleClient.ts, src/http/apiClients/models/people/RoleStatus.ts, src/http/resourceCollections/PeopleResourceCollection.ts, src/index.ts
Implement features to facilitate [#AB7870](https://dev.azure.com/statoil-proview/Fusion/_workitems/edit/7870).
=> Add API features to facilitate claimable roles

src/index.ts
Added `UserMenuSection` and `UserMenuSectionItem` to the list of exports from the `UserMenuContainer` in order to enable cleaner imports for users of the `useCustomUserMenuSection` hook.
=> Export user menu data types

src/core/PeopleContainer.ts, src/index.ts, src/utils/EventEmitter/index.ts
When implementing the [claimable roles feature](https://dev.azure.com/statoil-proview/Fusion/_workitems/edit/7870), we needed a way to change the status of a user role. Instead of doing this directly using the `PeopleClient`, we want to expose this functionality on the `PeopleContainer` instead so that we can handle updates in the cache and notify hooks of possible changes on a person.
**Changes**
- `PeopleContainer` is now an event emmiter that emits an event whenver a person is updated (currently only when a role changes status)
- Added a new hook `useEventEmitter` that accepts a custom handler function
- Added a new function `setRoleStatusForUser` on the `PeopleContainer` that should be used when updating user roles (instead of using the `PeopleClient` directly).
=> Adds function to set user role status on PeopleContainer

src/core/PeopleContainer.ts
If the cached role was at index 0, it would not be updated because we checked if `roleIndex` was truthy instead of checking if it was different from -1 (which is what `findIndex` returns if it can not determine the index).
In cases where the role was at index 0, it would not be updated in the local cache because 0 is not truthy in Javascript...
=> Update cached role in PeopleContainer if the role exists

package-lock.json, package.json, src/auth/AuthContainer.ts
1. User with expired token in token cache opens an app in fusion that requires a token from another app
2. The portal redirects to interactive signin for fusion
3. AD redirects back to fusion with id token in the hash/url fragment
4. The app requests token for it's own azure ad app
5. The portal redirects to interactive signin for the other app, but this time the empty fragment (#) is in the reply url since the AuthContainer uses window.location.href as reply url
6. AD looks for https://fusion.equinor.com/apps/something# in reply urls, but # in reply urls is not permitted
7. Login fails
Remove the hash/url fragment from the reply url
=> Fix consecutive sign in with invalid reply url

src/core/ContextManager.ts, src/http/apiClients/models/context/Context.ts, src/http/apiClients/models/context/ContextManifest.ts, src/http/apiClients/models/context/index.ts, src/http/apiClients/models/fusion/apps/AppManifest.ts, src/index.ts
Added property in appmanifest for defining contexttype used by app.
ContextManager now has a new hook that exposes the current useable contexttype for current app.
Removed contexttypes as a parameter from ContextManager hooks.
Contexttypes instead comes from the new useCurrentContextType Hook
=> Implementations for ContextTypes In AppManifest

src/core/ContextManager.ts
changed the useContectQuerty to expose the functions withing with an object instead of array. 
Wasnt praticularly clear what was going on using this, as a search call became something like this : 
useContextQuery()`[`3`]`("quertyText")
=> Changed useContextQuery to return an object instead of array.

src/core/FusionContext.ts, src/http/apiClients/BaseApiClient.ts, src/http/apiClients/ContextClient.ts, src/http/apiClients/DataProxyClient.ts, src/http/apiClients/FusionClient.ts, src/http/apiClients/OrgClient.ts, src/http/apiClients/PeopleClient.ts, src/http/apiClients/PowerBIClient.ts, src/http/apiClients/ReportClient.ts, src/http/apiClients/TasksClient.ts, src/http/apiClients/index.ts
If you need to make a request that's a bit to specific to implement in the api clients, you have to combine the service resolver and http client to make requests
Add get, post, put and patch to the base api client (and all the api clients by inheritance.) Each api client provides their base url, and the base api client uses that to combine the base url and path provided by the developer to make requests
=> Add http verb methods to api clients

src/app/AppContainer.ts
We need to be able to track how users navigate between apps. Which groupings of apps are used in which order. The current solution only tracked the previous app, but didn't work correctly as the current app was set to null before the previous app could be updated
Keep an array of the previous apps and add the current app to the head of the array when switching to a new app and log the entire array + the first item in the array to app insights
=> Keep and log an array of previous apps

src/http/HttpClient/IHttpClient.ts, src/http/HttpClient/index.ts
This should fix the following error:
```
DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED.
```
=> Corrected order of execution and added missing type param on interface

src/http/HttpClient/IHttpClient.ts, src/http/HttpClient/index.ts
Added option for providing a custom response parser when uploading files. Handy in case the API does not return anything, because then the default `JSON.parse` will throw...
I wantet to solve this using method two function overloads (this would be the cleanest solution for the user from an API point of view), e.g.:
```typescript
postFormAsync<TResponse, TExpectedErrorResponse>(
url: string,
form: FormData,
onProgress?: (percentage: number, event: ProgressEvent<XMLHttpRequestEventTarget>) => void,
responseParser?: (response: string) => TResponse
): Promise<HttpResponse<TResponse>>;
// Without TResponse type argument
postFormAsync<TExpectedErrorResponse>(
url: string,
form: FormData,
onProgress?: (percentage: number, event: ProgressEvent<XMLHttpRequestEventTarget>) => void,
responseParser?: …
```
=> Adds option for custom response parser on file upload and handle quotes in filename

src/auth/AuthContainer.ts, src/index.ts
There is a need to override the default auth containers functionality (e.g. teams SSO auth) but some of the properties and methods needed to achieve this is marked as private, restricting the ability to override.
Make all private properties and methods protected
=> Make the AuthContainer more overridable

src/core/FusionContext.ts
Ensure fusion context now sends existing history object for creating new context
=> Use existing history object in context

src/index.ts, src/utils/AbortControllerManager.ts
When performing continuous DOM checks (like width, height etc.) you would like to do so without locking the process (blocking the browser from rendering) and _after_ a repaint. Using setTimeout will add the callback after repaints, but will block  further repaints until all operations are completed. This will "freeze" the browser completely when using recursive setTimeouts. RequestAnimationFrame will place the callback _before_ the repaint but does not block the browser from repainting
Nesting requestAnimationFrame and setTimeout will ensure operations does not block the process and is performed after paint.
=> Function to enqueue async operations

src/index.ts
Export all error types that can be thrown by `HttpClient` so that we can have type safe error handling, e.g.:
```typescript
try {
this.httpClient.putAsync<.....................
} (error) {
const httpClientError = error as HttpClientError;
...
}
```
=> Export all error types that can be thrown from HttpClient

src/core/ContextManager.ts
So that is pushes to history when url is different, not the same
=> Flipp newUrl check.

src/app/AppContainer.ts
It was checking that there was a previous app and that the key does not match the current app, but when the app history is empty it will never add an app to the history and the entire condition will always be false. Refactoring the condition to check if the previous app is _not_ set **or** the previous app key does not match the current app key
=> App selection history is not kept

src/app/AppContainer.ts, src/core/PeopleContainer.ts, src/http/apiClients/PeopleClient.ts, src/utils/AbortControllerManager.ts
- enqueueAsyncOperation spent most of its time regestering events on the abort signal. Refactored it to not perform the operation if the signal is aborted. Otherwise go ahead
- Catch error when performing people api signin
- Trigger rerender of components using the useCurrentApp() hook when changes are made to the app manifests
- Protect agains empty strings/null in person hooks
=> Minor bug fixes

src/core/ContextManager.ts
The relevant change is on line 263.
- Context Selector
We are using the new context selector in the Query app, and the problem we are seeing is that clearing the context does clear the context in local storage, but the project name is still visible until page reload. I managed to reproduce the problem in fusion components storybook, and it didn't seem like the local context state in the `useCurrentContext` hook was updated after clearing the context.
This problem was kind of hard to debug and test because the involved components are distributed between multiple packages (fusion portal / fusion cli, fusion-components and fusion-api), so I do not know for sure that this will solve the issue.
My theory however is that the `setContext` callback in the `useCurrentContext` hook is not updated …
=> useCurrentContext - Update callback when current context changes

src/core/ContextManager.ts
Added a try catch in getCurrentContextAsync. As call to context api with a non-existing context Id caused an unhandled exception.
=> GetCurrentContextAsync - Handle exceptions

.github/workflows/buildAndPublish.yml, package.json
The version.ts file is used to tag http request etc. with the current fusion api version and needs to be updated when the package version is changed. Currently this is done in the build and publish action, but after adding more policies to the master branch (build action and review) the build and publish action fails when pushing the version.ts change
Perform the change to version.ts when running `npm version patch` by adding an npm script `version` which is run AFTER incrementing version but BEFORE commit
=> Update version ts when bumping

src/http/apiClients/models/people/PersonContract.ts, src/http/apiClients/models/people/PersonProject.ts
Version 3 of the people API which is used by `PeopleClient` does not correspond to the models defined in `fusion-api`. This PR aligns the models with the response model defined in the people API.
Technically a breaking change. Should we bump the major version of `fusion-api` or do we have sufficient control over the usages so that we can treat this as a patch or minor version upgrade?
As far as I can see, we only have to update `PersonPositionCard.stories` in `fusion-components`.
Example response from
`GET https://pro-s-people-ci.azurewebsites.net/persons/26c3e768-7bb4-4bbc-b574-ba55edbd9d37?$expand=positions,contracts,roles`
```json
{
"positions": [],
"contracts": [
{
"id": "b9cf46e1-22d7-4e85-bbdc-478433da985d",
"name": "Software & engineering",
"contractNumber": "456034",
"companyId": …
```
=> Align person model with api contract

src/app/AppContainer.ts, src/core/ContextManager.ts, src/core/FusionContext.ts
The feature logger keeps track of the current context selected so that it can be added as metadata on each feature log from Fusion. The problem is that when selecting a new app, that context is stil set on the feature logger and added to the app selection log. Even if the app does not support context (e.g. tasks.) It also causes apps that don't support the same context type to be logged with incorrect context
Clear the current context from the feature logger when switching to an app that does not support the selected context
=> Feature logger logs context for apps that don't support context

src/core/FusionContext.ts, src/http/HttpClient/index.ts
Each app gets its own HttpClient with it's own queue of requests in progress. This defeats the purpose of the reusable requests in progress.
Make the requests in progress distributed
=> Make HttpClient.requestsInProgress distributed

src/app/AppContainer.ts, src/http/HttpClient/index.ts
- Retries failed requests (e.g. 502 etc.) automatically in a given "timeframe"
- Also adds optional name etc. to app registration to display when the app is running through fusion CLI
=> Retry http requests automatically

src/core/ContextManager.ts
ensureCurrentContextExistsInUrl converted to arrow function to maintaing proper scope to this.
=> ensureCurrentContextExistsInUrl scope bug

src/core/ContextManager.ts
ensureCurrentContextExistsInUrl check that we are actually in an app. Else you end up with context in portal url also
=> ensureCurrentContextExistsInUrl - In app check 

src/http/HttpClient/IHttpClient.ts, src/http/HttpClient/index.ts, src/http/models/BlobContainer.ts
- Create new type `BlobContainer`
- `{ blob, fileName }`
- Return `BlobContainer` in `getBlobAsync`
- Create new function `getFileAsync` for returning File (identical to previous `getBlobAsync` implementation)
- Update interface `IHttpClient`
Fixes #180
=> Separate get-functions for Blob and File

src/auth/AuthCache.ts, src/auth/AuthContainer.ts
- AuthCache:
- Rename enum `TokenCacheKey` => `CacheKey`
- Add new constant `CacheKey.APP_LOGIN_LOCK `
- Add new functions for setting and accessing a login-lock
- `setAppLoginLock`, `clearAppLoginLock`, `isAppLoginLocked`
- AuthContainer
- `loginAsync`: skip login if some other login process has started. Implemented by using the new login-lock functions of AuthCache
- `registerAppAsync`: clear the app's login-lock when the app has successfully gotten a token
=> Avoid parallel app logins

src/auth/AuthCache.ts, src/auth/AuthContainer.ts
`AuthContainer`:
- `handleWindowCallbackAsync`:
- Force window reload when setting `redirectUrl` after login
- `registerAppAsync`
- When setting or clearing lock, use clientId of resolved app instead of param
- Clear login-lock (if owned by the app) when app exists and has token
`AuthCache`:
- When clearing lock, remove the key entirely instead of setting it to `""`
Closes #198
=> Auth: Force redirect routing, incl. some login-lock improvements

src/http/apiClients/PeopleClient.ts, src/http/apiClients/PowerBIClient.ts, src/http/apiClients/models/powerbi/PoweBIDataset.ts, src/http/resourceCollections/PowerBIResourceCollection.ts
There is no get request for the api-signin and you get a 405 everytime this code is called.
This should probably be a post, as thats whats used elsewhere.
Seeing as this has been "wrong" for a long time, one might wonder if this code can be removed ?
Think this fix should atleast fix the failed get request you get every time you load fusion.
=> People Client does a non-exsiting get request to api-signing

src/hooks/useSignalRHub.ts, src/http/resourceCollections/FusionResourceCollection.ts
The SinglaR hub disconnected every hour because the token timed out.
Changed the implementation to let the backend deal with negotiation details and token handling
=> Bugfix - SignalR hub disconnect every hour

src/http/apiClients/DataProxyClient.ts, src/http/apiClients/models/dataProxy/handover/HandoverItem.ts, src/http/apiClients/models/dataProxy/handover/HandoverStatus.ts, src/http/hooks/dataProxy/useHandover.ts, src/http/resourceCollections/DataProxyResourceCollection.ts
DataProxy getHandover and getHandoverChildren updated to use new context endpoints.
HandoverItem update with a few new and missing fields.
DataProxyResourceCollection update with new urls for handover and handoverChildren.
useHandover update to reflect above changes.
This is a breaking change, but I can not find any implementation of these endpoints.
I believe these were just created for future use. 
The ony place I can find the handover beeing used is in the PDP apps (handover and operation garden). 
These gardens uses legacy api that still resides in the project-portal repo.
=> DataProxy Handover api for context

src/http/apiClients/ReportClient.ts
added a custom response parsers. As the response is void, the parser fail.
=> fix: Report Client - checkContextAccess resolve reponse

src/utils/url.ts
remove positive lookbehind, since safari does not support this atm
=> fix: url sanitize

src/http/apiClients/models/dataProxy/handover/HandoverLineStatus.ts
Was told Not Appliable was not applicable, this looks to be wrong, and is in fact 'na', this has been changed
=> HandoverLineStatus string updated

src/http/apiClients/DataProxyClient.ts, src/http/apiClients/models/dataProxy/handover/HandoverItem.ts, src/http/apiClients/models/dataProxy/handover/HandoverLineStatus.ts, src/http/apiClients/models/dataProxy/handover/OperationItem.ts, src/http/apiClients/models/dataProxy/handover/OperationLineStatus.ts, src/http/apiClients/models/dataProxy/index.ts, src/http/resourceCollections/DataProxyResourceCollection.ts
It is mostly the same as the old handoverItem endpoint, but has some extra fields.
LineStatus fields removed again from the HandoverItem model and moved into new OperationItem.
OperationItem model is handoverItem pluss these two fields.
There are other LineStatus fields that could be added here later. But for now they will not be exposed by the backend, as they wont be used by garden currently.
=> New endpoint in handover to be used for operation garden.

src/core/ContextManager.ts
Filter context history. 
The context history will now be get filtered based on the contextTypes that are in use by the app. 
Previsouly it would just show the "raw list", which could include contexts that was not usable in current app. 
currenctContext routing has been changed to use replace instead of push. 
Pushing caused issued where user expected back button to got back to previous page and not to the previous context or just in a circle with the current context. Making it look like the back button didnt no anything
=> Contextmanager filter contexthistory and replace history

src/core/ContextManager.ts
Previous solution for filtering valid context types was in violation  with hook rules and created errors in the console when implemented.
Have reimplemented the solution in a slighly different way that should follow the rules properly.
=> fix: Context Manager - useContextHistory hook rule violation

src/core/NotificationCenter.tsx
In fusion-components, I want to have the opportunity to hide one of the action buttons (Cancel, Confirm) from the modal. Introducing an optional bool that I can set to true if I want to hide the cancel button.
```typescript
const createNotification = useNotificationCenter();
createNotification({
level: 'high',
title: 'Copied to clipboard',
confirmLabel: 'Close',
hideCancel: true,
body: "",
});
```
=> add an optional bool to Notification Request Type

src/http/apiClients/ReportClient.ts, src/http/apiClients/models/report/RlsConfiguration.ts, src/http/apiClients/models/report/RlsValidationError.ts, src/http/resourceCollections/ReportResourceCollection.ts
new Report client endpoint, validateRlsConfiguration. Used to validate rls configuration input before saving report.
Added new RlsValidationError model that can be returned from the validateRlsConfiguration endpoint if the configuration is not valid.
Updated RlsConfiguration model to be inline with the updated version that is being used in the indevelopment Report Admin.
The changes to the model might look like alot, but it is fairly minor.
Generally the model has been update more strictly in line with the predefined rls-configuration.json schema defined by the backend.
Both in names used and types
=> Report Client - new RLS Validation endpoint

src/http/apiClients/models/org/OrgProject.ts, src/http/apiClients/models/org/OrgProjectType.ts, src/http/apiClients/models/org/Position.ts, src/index.ts
Need pimsWriteSyncEnabled and disableSync on OrgProject model for solving this user story:
https://statoil-proview.visualstudio.com/Fusion/_backlogs/backlog/Operations%20and%20Improvements/Stories/?showParents=true&workitem=22526
orgAdminEnabled on OrgProject model, and resourceType on Position model is currently in use in Pro Org and Org Admin apps, so including those as well
=> feat: added properties to OrgProject and Position models

README.md, src/hooks/useAbortableRequest.ts, src/index.ts
Hook for making HTTP requests abortable.
Utilizes the abortController provided by fusion-api.
=> feat: abortable request hook
